# Generated by Django 4.0.3 on 2022-04-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
