# Generated by Django 4.0.3 on 2022-05-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_remove_lecture_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
